spring:
  datasource:
    initialization-mode: always
    platform: h2
    url: jdbc:h2:mem:mediadb;
    username: sa
    password: null

api:
  connect:
    path: /
  bff:
    path: /
  services:
    account-service: http://account-service.ns-zcp-admin-01.svc.cluster.local:8080
    contents-service: http://contents-service.ns-zcp-admin-01.svc.cluster.local:8080
    recommendation-service: http://recommendation-service.ns-zcp-admin-01.svc.cluster.local:8080