spring:
  datasource:
    initialization-mode: always
    platform: h2
    url: jdbc:h2:mem:mediadb;
    username: sa
    password: null

api:
  connect:
    path: /
  bff:
    path: /
  services:
    account-service: http://account-service.default.svc.cluster.local:8080
    contents-service: http://contents-service.default.svc.cluster.local:8080
    # recommendation-service: http://recommendation-service.not.available:8080
    recommendation-service: http://recommendation-service.default.svc.cluster.local:8080